/* Ghost Shopper — Admin Dashboard Data */

export const businesses = [
  {
    id: 'ramirez-vazquez-001',
    name: 'Ramírez Vázquez Bienes Raíces',
    slug: 'ramirezvazquez',
    website: 'ramirezvazquez.paoloose.site',
    fullUrl: 'https://ramirezvazquez.paoloose.site',
    location: {
      city: 'Ciudad de México',
      state: 'CDMX',
      country: 'México',
      coords: { lat: 19.4326, lng: -99.1332 },
    },
    industry: 'Inmobiliaria Residencial',
    founded: '2019',
    employees: '4-10',
    status: 'finished',
    score: 6.2,
    context: `Ramírez Vázquez Bienes Raíces es una agencia inmobiliaria con sede en Ciudad de México, México. Fundada en 2019, opera con un equipo de 4-10 personas. Su propuesta de valor se centra en brindar seguridad y certeza jurídica tanto a vendedores como compradores.`,
    lastAuditAt: '2025-05-24T22:00:00Z',
    crawlData: {
      pagesFound: 14,
      totalImages: 48,
      formsDetected: 2,
      hasWhatsApp: true,
      hasEmail: true,
      hasPhone: true,
      hasChatbot: false,
      hasLogin: true,
      hasBlog: false,
      socialMedia: {
        facebook: 'https://www.facebook.com/profile.php?id=61557971802285',
        instagram: 'https://www.instagram.com/ramirezvazquezmx/',
        youtube: 'https://www.youtube.com/@bienesraicesramirezvazquez',
        x: 'https://x.com/RVazquez_BR',
      },
      seo: {
        title: 'Ramirez Vazquez Bienes Raices | vender mi propiedad en ciudad de mexico',
        description: 'Somos una agencia inmobiliaria enfocada en brindar seguridad y certeza jurídica...',
        hasSchema: false,
        hasOpenGraph: false,
        hasTwitterCard: false,
        keywords: ['bienes raíces', 'departamentos', 'cdmx', 'inmobiliaria'],
      },
      performance: {
        mobileSpeed: 42,
        desktopSpeed: 71,
        firstContentfulPaint: '2.8s',
        largestContentfulPaint: '4.1s',
        cls: 0.12,
      },
      ux: {
        hasPricingVisible: false,
        hasTestimonials: false,
        hasVirtualTour: false,
        hasAgentPhotos: true,
        hasCTAAboveFold: true,
        navigationItems: 7,
        propertyCount: 12,
      },
      trustSignals: {
        hasReviews: false,
        hasCertificates: false,
        hasYearsBadge: true,
        hasTeamSection: true,
        hasPrivacyPolicy: true,
      },
      contentAnalysis: {
        wordCount: 1847,
        languages: ['es'],
        hasSpellingErrors: 0,
        readabilityScore: 68,
        hasDuplicateContent: false,
        imagesWithoutAlt: 3,
      },
    },
    metrics: {
      responseRate: 0,
      avgResponseTime: null,
      leadsPerMonth: 0,
      conversionRate: 0,
      competitors: [],
    },
  },
  {
    id: 'pendry-mexico-002',
    name: 'Pendry Residences Mexico City',
    slug: 'pendrymexico',
    website: 'pendrymexicocityresidences.paoloose.site',
    fullUrl: 'https://pendrymexicocityresidences.paoloose.site',
    location: { city: 'Ciudad de México', state: 'CDMX', country: 'México', coords: { lat: 19.4167, lng: -99.1667 } },
    industry: 'Residencias de Lujo',
    founded: '2024',
    employees: '10-20',
    status: 'waiting',
    score: null,
    lastAuditAt: null,
    context: `Pendry Residences Mexico City ofrece una colección limitada de 20 residencias privadas en Roma Norte, Ciudad de México. Ganador del premio Urban Design & Architecture 2026. Operado por Mexico City Residential Development Group, LLC.`,
    crawlData: {
      pagesFound: 11, totalImages: 48, formsDetected: 2,
      hasWhatsApp: true, hasEmail: true, hasPhone: true,
      hasChatbot: false, hasLogin: true, hasBlog: false,
      socialMedia: {},
      seo: { title: 'Pendry Mexico | Contemporary Luxury Residences in Mexico City', hasSchema: false, hasOpenGraph: false, keywords: ['luxury residences', 'roma norte', 'cdmx', 'pendry'] },
      performance: { mobileSpeed: 62, desktopSpeed: 81 },
      ux: { hasPricingVisible: true, hasTestimonials: false, hasVirtualTour: false, propertyCount: 20 },
      trustSignals: { hasReviews: false, hasCertificates: true, hasYearsBadge: false, hasTeamSection: false, hasPrivacyPolicy: true },
      contentAnalysis: { wordCount: 2400, readabilityScore: 72 },
    },
    metrics: { competitors: [] },
  },
]

export const contacts = [
  {
    id: 'contact-001',
    businessId: 'ramirez-vazquez-001',
    name: 'Jorge Ramírez',
    email: 'contacto@ramirezvazquez.com',
    responseTime: 2.5,
    personalization: 6.5,
    clarity: 7.2,
    cta: 5.8,
    score: 6.2,
    emails: [
      {
        direction: 'sent',
        subject: 'Reporte gratuito de su presencia digital — Ghost Shopper',
        body: `Estimado equipo de Ramírez Vázquez Bienes Raíces,\n\nMi nombre es Sofía Méndez y soy consultora de estrategia digital en Ghost Shopper.\n\nDurante las últimas semanas, nuestro sistema ha rastreado y analizado la experiencia digital de su agencia. Hemos identificado oportunidades significativas para mejorar la captación de leads.\n\nNos gustaría compartir con ustedes un reporte ejecutivo completamente gratuito que incluye:\n\n• Análisis de velocidad y performance móvil\n• Evaluación del embudo de conversión\n• Auditoría de UX/UI orientada a ventas\n• Benchmarking contra 3 competidores directos\n• Recomendaciones accionables priorizadas\n\n¿Les gustaría recibirlo? Solo responden a este correo y lo enviamos en las próximas 24 horas.\n\nSaludos cordiales,\nSofía Méndez\nGhost Shopper — Dream Team`,
        date: '15 May',
        status: 'responded',
        aiScore: 7.5,
      },
      {
        direction: 'received',
        subject: 'Re: Reporte gratuito de su presencia digital',
        body: `Hola Sofía,\n\nMuchas gracias por contactarnos. Estoy muy interesado en recibir el reporte ejecutivo de nuestra agencia. Hace tiempo que sospechamos que nuestra web no está rindiendo como debería.\n\nAdemás, me gustaría conocer más sobre el servicio de suscripción mensual. Estamos abiertos a mejorar nuestros procesos.\n\nUn saludo,\nJorge Ramírez\nDirector — Ramírez Vázquez Bienes Raíces`,
        date: '16 May',
        status: 'responded',
        aiScore: 6.8,
      },
    ],
  },
  {
    id: 'contact-002',
    businessId: 'pendry-mexico-002',
    name: 'Pendry Concierge',
    email: 'inquiry@pendryresidencesmexicocity.com',
    responseTime: null,
    personalization: null,
    clarity: null,
    cta: null,
    score: null,
    emails: [
      {
        direction: 'sent',
        subject: 'Auditoría digital gratuita — Pendry Residences Mexico City',
        body: `Estimado equipo de Pendry Residences Mexico City,\n\nMi nombre es Sofía Méndez, consultora de Ghost Shopper. Evaluamos la experiencia digital de residencias de lujo en Ciudad de México.\n\nNos gustaría compartir un análisis gratuito de su presencia web y canales de contacto.\n\n¿Les gustaría recibirlo?`,
        date: '20 May',
        status: 'waiting',
        aiScore: null,
      },
    ],
  },
]

export const audits = [
  {
    id: 'audit-001',
    businessId: 'ramirez-vazquez-001',
    businessName: 'Ramírez Vázquez Bienes Raíces',
    createdAt: '2025-05-24T22:00:00Z',
    model: 'kimi-k2.6',
    status: 'completed',
    totalSteps: 12,
    score: 6.2,
    findings: [
      { category: 'Response Time', severity: 'bad', title: 'Tiempo de respuesta crítico', description: 'El sitio tarda 4.1s en cargar en móvil. El 72% de leads en CDMX navegan desde smartphones.', recommendation: 'Optimizar imágenes (AVIF/WebP), lazy-loading, y reducir JS bloqueante.' },
      { category: 'Conversion Funnel', severity: 'warn', title: 'Sin precios visibles', description: 'Ninguna propiedad muestra precio. En estudios de usabilidad inmobiliaria, esto genera abandono temprano del 40%.', recommendation: 'Mostrar rango de precios o "desde $X" en cada tarjeta de propiedad.' },
      { category: 'Trust', severity: 'bad', title: 'Ausencia de testimonios', description: 'Sin reviews, testimonios ni badges de certificación. La compra de inmueble requiere alto nivel de confianza.', recommendation: 'Agregar sección de testimonios de clientes y certificaciones de AMPI.' },
      { category: 'SEO', severity: 'warn', title: 'Schema markup ausente', description: 'Sin structured data (RealEstateListing, Organization, LocalBusiness). Google no enriquece los snippets.', recommendation: 'Implementar schema.org/RealEstateListing y LocalBusiness JSON-LD.' },
      { category: 'Mobile UX', severity: 'bad', title: 'Formularios rotos en móvil', description: 'El formulario de contacto no tiene autocomplete y el botón de WhatsApp es pequeño en pantallas <360px.', recommendation: 'Aumentar hit areas a 44px mínimo y agregar autocomplete a todos los inputs.' },
    ],
  },
  {
    id: 'audit-002',
    businessId: 'ramirez-vazquez-001',
    businessName: 'Ramírez Vázquez Bienes Raíces',
    createdAt: '2025-04-12T16:45:00Z',
    model: 'deepseek-v4-pro',
    status: 'completed',
    totalSteps: 18,
    score: 5.8,
    findings: [
      { category: 'Mobile UX', severity: 'bad', title: 'Imágenes sin alt text', description: '3 imágenes de propiedades carecen de texto alternativo. Impacta SEO y accesibilidad.', recommendation: 'Agregar alt descriptivo a todas las imágenes de propiedades.' },
      { category: 'SEO', severity: 'warn', title: 'Meta description duplicada', description: 'Todas las páginas de propiedades comparten la misma meta description.', recommendation: 'Generar meta descriptions únicas por propiedad con precio y ubicación.' },
      { category: 'Trust', severity: 'warn', title: 'Sin política de privacidad visible', description: 'Aunque existe la página, el link en el footer es de bajo contraste.', recommendation: 'Hacer el link de privacidad más visible y agregar checkbox de consentimiento en el formulario.' },
    ],
  },
  {
    id: 'audit-003',
    businessId: 'ramirez-vazquez-001',
    businessName: 'Ramírez Vázquez Bienes Raíces',
    createdAt: '2025-03-08T11:20:00Z',
    model: 'glm-5.1',
    status: 'completed',
    totalSteps: 9,
    score: 5.2,
    findings: [
      { category: 'Performance', severity: 'bad', title: 'LCP excedido', description: 'Largest Contentful Paint de 5.2s supera el umbral recomendado de 2.5s.', recommendation: 'Preload hero images y usar font-display: swap.' },
      { category: 'Content', severity: 'warn', title: 'Contenido escaso', description: 'Promedio de 154 palabras por página de propiedad. Ideal: 300+.', recommendation: 'Expandir descripciones con amenities, vecindario y transporte cercano.' },
    ],
  },
]
